### ISSUE TITLE
如何将参考文献设置为上标？

### ISSUE THREAD

**Issue by YuPeize** [njuHan/njuthesis-nju-thesis-template#10]
![image](https://user-images.githubusercontent.com/26381026/74085904-e2ef6880-4ab8-11ea-8065-0151ce73eef7.png)
编译出来是这样的

**Comment by jiangqy** [comment]
定义新命令：
\newcommand{\upcite}[1]{\textsuperscript{\textsuperscript{\cite{#1}}}}

正文使用：
\upcite{XXX}

不知道是否规范。

**Comment by yumath** [comment]
@jiangqy 不过这种方法没办法在图片标题里cite

**Comment by jiangqy** [comment]
图片里没试过，我后来用了另一个repo：https://github.com/Haixing-Hu/nju-thesis .这个里直接就是上标引用，也许可以找到相关设置。 @yumath

**Comment by guixianjin** [comment]
要实现为上标显示，可以修改 njuthesis.cls 文件如下一行
```
...
\bibliographystyle{gbt7714-2005}
%\setcitestyle{super,square}
\setcitestyle{square}
...
```
改为：
```
...
\bibliographystyle{gbt7714-2005}
\setcitestyle{super,square} 
%\setcitestyle{square}
...
```
- - -

By the way, 如果不想用当前默认的 \bibliographystyle{gbt7714-2005} 格式的参考文献格式，也可以修改 njuthesis.cls 文件如下一行的命令
```
...
\bibliographystyle{gbt7714-2005}
...
```
改为：
```
...
\bibliographystyle{plain}  % 这里也可以用其他格式，参见刘海洋前辈 《Latex 入门》书籍第三章
...
```
