### ISSUE TITLE
公式字体问题

### ISSUE THREAD

**Issue by jiangqy** [njuHan/njuthesis-nju-thesis-template#11]
Hi, 

感谢分享。

请教下这个模板显示的公式字体似乎与直接用latex写的文档的字体稍有不同，请问如何显示成正常公式字体？

例如使用如下代码：
`
字体测试

\begin{itemize}
\item 英文小写字母：$x$
\item 英文黑体小写字母：${\bf x}$
\item 英文黑体小写斜体字母：${\boldsymbol x}$
\item 英文大写字母：$X$
\item 英文黑体大写字母：${\bf X}$
\item 英文黑体大写斜体字母：${\boldsymbol X}$
\end{itemize}
`

结果显示为：
<img width="321" alt="image" src="https://user-images.githubusercontent.com/14566109/75246061-f36a4780-5809-11ea-8735-66ca9dc48c44.png">

而正常显示为：
<img width="135" alt="image2" src="https://user-images.githubusercontent.com/14566109/75246195-3fb58780-580a-11ea-9778-2a7a5283023d.png">

其中最明显的，${\bf x}$是明显不一样的。

谢谢。

**Comment by njuhan** [comment]
本模板使用Times New Roman风格的math font.
如果想用默认的Computer Modern math font, 请在 .cls文件中删除txfonts宏包的引用及其相关使用.

**Comment by svdbase** [comment]
非常谢谢，问题已解决。

**Comment by jiangqy** [comment]
非常感谢，问题已解决。 @njuHan
