### ISSUE TITLE
Undefined control sequence: \CJKunderlinecolor and \CJKunderline

### ISSUE THREAD

**Issue by bctian** [njuHan/njuthesis-nju-thesis-template#17]
XeLaTex cannot complie the sample.tex and reports undefiled control sequence.

I have removed the line `\renewcommand*{\CJKunderlinecolor}{\color{black}}`, and add following two lines to work around:
```
\newcommand*{\CJKunderlinecolor}{\color{black}}
\newcommand*{\CJKunderline}[1]{\uline{#1}}
```

Maybe something has changed in the newest version of xeCJK.

**Comment by yuqALL** [comment]
> \newcommand*{\CJKunderlinecolor}{\color{black}}
> \newcommand*{\CJKunderline}[1]{\uline{#1}}

solve the problem

**Comment by xuyxu** [comment]
Thanks @yuqZY, your solution also works on Texpad ;-)

**Comment by ChristmasWang** [comment]
Nice Solution! Thank U! @bctian

**Comment by db12138** [comment]
Thank U @bctian
