### ISSUE TITLE
如何调整 reference 中的人名格式？

### ISSUE THREAD

**Issue by guixianjin** [njuHan/njuthesis-nju-thesis-template#19]
![image](https://user-images.githubusercontent.com/19357015/111563929-d5d09d00-87d3-11eb-8ee2-386c03949ff1.png)

如图所示，当前参考文献的格式似乎不是非常规范，请问如何把人名都调整为仅首字母大写并去除 TCP[J] 等式样？

**Comment by guixianjin** [comment]
自问自答。
如果不想用当前默认的 \bibliographystyle{gbt7714-2005} 格式的参考文献格式，也可以修改 njuthesis.cls 文件如下一行的命令
...
\bibliographystyle{gbt7714-2005}
...
改为：

...
\bibliographystyle{plain}  % 这里也可以用其他格式，参见刘海洋前辈 《Latex 入门》书籍第三章
...

但按照这一方式修改后，仍然存在一些问题，例如 reference 断词出错， 如下文图片中第二行行首的 s：
![image](https://user-images.githubusercontent.com/19357015/111869771-d9267d00-89bb-11eb-8b68-e4b2f3f86ad5.png)

如果在 sample.tex 导言区增加如下命令，设置断词的包
```
...
\usepackage[american]{babel}
...
```
这一修改方式能够解决断词问题，但又会导致其他问题，例如标题 “第一章 xxx" 变为 "Chapter 1 xxx", 且标题“参考文献” 变为 “Reference ”。
目前还没有更好的办法解决。

**Comment by dlee992** [comment]
确实如此，原有的引用格式比较丑陋，或许需要懂相关语法的人去改动一下那个 bst 文件，才是最好的方式吧。我看很多人最后都换用了其他引用格式.....

**Comment by njuhan** [comment]
详见 【GB_T%207714-2005】文后参考文献著录规则.pdf
