### ISSUE TITLE
关于引用网页

### ISSUE THREAD

**Issue by AllenKaiChen** [njuHan/njuthesis-nju-thesis-template#20]
按照网上的一般方法写的网页的bib，引用的时候不成功，请问在该模板下有什么要求么？网上给的格式类似这种：
@Misc{timmurphy.org,

howpublished = {\url{http://timmurphy.org/2009/07/22/line-spacing-in-latex-documents/}},

note = {Accessed April 4, 2010},

title = {Line Spacing in LaTeX documents},

author = {Murphy, Timothy I}

}

**Comment by AllenKaiChen** [comment]
Forget about that

**Comment by JackyTown** [comment]
同问，这个问题如何解决呀？
