### ISSUE TITLE
希望获知作者真实姓名以列入新版njuthesis贡献列表

### ISSUE THREAD

**Issue by atxy-blip** [njuHan/njuthesis-nju-thesis-template#23]
学长您好！

目前NJU Linux User Group组织承担了毕业论文模板的维护工作，推出了[NJUthesis](https://github.com/nju-lug/NJUThesis)这一全新模板。我们希望能统筹现存的工作，对历史存在的模板进行总结，因而希望将您以及您的njuthesis列入贡献列表，也特此前来询问真实姓名。我已将一份新版模板的说明文档存于附件供您参考。

如果您赞成以上提议，不妨与我通过邮箱交流！（181850195 AT smail.nju.edu.cn）

[njuthesis.pdf](https://github.com/njuHan/njuthesis-nju-thesis-template/files/7189309/njuthesis.pdf)

**Comment by njuhan** [comment]
谢谢啦! 可以把现有工作链接到你们维护的模板，贡献列表列出贡献者的github id 吧.  
12级本科计算机系的老学长已经把校邮箱密码忘记了，哈哈哈哈
