### ISSUE TITLE
算法Algorithm 包中无法定义function ,我在.cls中加上\usepackage{algpseudocode} 中进行了支持

### ISSUE THREAD

**Issue by db12138** [njuHan/njuthesis-nju-thesis-template#25]
.cls 文件修改为
![image](https://user-images.githubusercontent.com/23103161/157261971-aa10f5e0-e136-4b7f-9aea-6f1bd1548213.png)

tex中algorithm 模块 添加function
![image](https://user-images.githubusercontent.com/23103161/157262072-4b92e93f-e6ef-4d54-8b18-7f198cd3bdb8.png)

pdf 效果
![image](https://user-images.githubusercontent.com/23103161/157261996-f2958000-7a5a-41f2-852e-7dadaaa57695.png)

**Comment by njuhan** [comment]
谢谢！ 关于 algorithm packages, 这个文档有详细介绍：
https://tex.stackexchange.com/questions/229355/algorithm-algorithmic-algorithmicx-algorithm2e-algpseudocode-confused
