### ISSUE TITLE
申请转载

### ISSUE THREAD

**Issue by latexstudio** [njuHan/njuthesis-nju-thesis-template#5]
我是 http://www.latexstudio.net  申请模板发布转载，盼复！

**Comment by njuhan** [comment]
请遵循GNU General Public License v2.0，
请在[转载页面](http://www.latexstudio.net/archives/51663.html)的说明前写上[源仓库地址](https://github.com/njuHan/njuthesis-nju-thesis-template)，
感谢对LaTeX在中国的推广做出贡献。
