### ISSUE TITLE
首页及摘要页的下划线颜色是蓝色

### ISSUE THREAD

**Issue by zhy91** [njuHan/njuthesis-nju-thesis-template#8]
虽然 `njuthesis.cls` 中已经设置了 `\renewcommand*{\CJKunderlinecolor}{\color{black}}`，但是首页及摘要页涉及到填写信息的下划线编译之后全都变成蓝色了。请问应该怎么设置成正常的黑色？（在网上有过搜索，需要设置 `\def\CJKunderlinecolor{\color{black}}`，但是并没有用）
我的环境：Windows 10 + TeX Live 2017

**Comment by njuhan** [comment]
大部分同学使用CTEX编译出来都是黑色的，蓝色的可能是环境问题

**Comment by RukawaKaede** [comment]
> 虽然 `njuthesis.cls` 中已经设置了 `\renewcommand*{\CJKunderlinecolor}{\color{black}}`，但是首页及摘要页涉及到填写信息的下划线编译之后全都变成蓝色了。请问应该怎么设置成正常的黑色？（在网上有过搜索，需要设置 `\def\CJKunderlinecolor{\color{black}}`，但是并没有用）
> 我的环境：Windows 10 + TeX Live 2017

你好，我的也是蓝色，请问你解决了吗，能否告知一下:-)

**Comment by zhy91** [comment]
> > 虽然 `njuthesis.cls` 中已经设置了 `\renewcommand*{\CJKunderlinecolor}{\color{black}}`，但是首页及摘要页涉及到填写信息的下划线编译之后全都变成蓝色了。请问应该怎么设置成正常的黑色？（在网上有过搜索，需要设置 `\def\CJKunderlinecolor{\color{black}}`，但是并没有用）
> > 我的环境：Windows 10 + TeX Live 2017
> 
> 你好，我的也是蓝色，请问你解决了吗，能否告知一下:-)

你好，我没有解决这个问题，而是换了其他模板，然后整合好几个模板的设置，修修补补凑合用了。。
现在好像新出了TeX Live 2020？可以升级试试^_^

**Comment by RukawaKaede** [comment]
> > > 虽然 `njuthesis.cls` 中已经设置了 `\renewcommand*{\CJKunderlinecolor}{\color{black}}`，但是首页及摘要页涉及到填写信息的下划线编译之后全都变成蓝色了。请问应该怎么设置成正常的黑色？（在网上有过搜索，需要设置 `\def\CJKunderlinecolor{\color{black}}`，但是并没有用）
> > > 我的环境：Windows 10 + TeX Live 2017
> > 
> > 
> > 你好，我的也是蓝色，请问你解决了吗，能否告知一下:-)
> 
> 你好，我没有解决这个问题，而是换了其他模板，然后整合好几个模板的设置，修修补补凑合用了。。
> 现在好像新出了TeX Live 2020？可以升级试试^_^

啊哈，;-)，我参考别人的模板，发现问题了，修改njuthesis.cls如下：
```
% \renewcommand*{\CJKunderlinecolor}{\color{black}}
\RequirePackage{xeCJKfntef}
\xeCJKsetup{ underline/format = \color{black} }
```
把原来的`\renewcommand*{\CJKunderlinecolor}{\color{black}}`给注释掉，然后增加下面两行。
